# 안전 작동 검사

- 어플리케이션이 동작 도중에 생성하는 다양한 연산 결과값을 동적으로 확인하고 안전하게 처리하는 구문
- 조건을 통해 패스 및 스크립트 중단으로 사용자 입장에서 치명적인 런타임 에러 등을 사전에 방지

## Assertion

- `assert(_:_:file:line:)` 함수를 사용
    - K : 예제에서도 매개변수가 저 순서대로 되어있는데, 실제로 해보니까 file, line이 앞에 왔고, 내장함수 형태에 두 매개변수가 없었음
- assert 함수는 ‘디버깅 모드'에서만 동작
- 배포하는 어플리케이션에서는 해당 구문이 제외됨
- 예상했던 **조건의 검증을 위하여** 사용
- Assert 함수의 조건이 false인 경우, 메세지를 표시하고 그 시점의 모든 스크립트를 중단

```swift
var someInt : Int? = 0

// 형태
// assert(Bool 타입 조건, 실패 시 메세지)

assert(someInt == 0) // 패스
assert(someInt == 0, "someInt가 0이 아닙니다.") // 패스

assert(someInt == 1) // Assertion failed
assert(someInt == 1, "someInt가 0이 아닙니다.") // Assertion failed: someInt가 0이 아닙니다.

someInt = nil
assert(someInt != nil, "someInt = nil") // Assertion failed: someInt = nil

func ageCheckWithAssert(inputAge : Int?) {
  
  // 조건문이 true면 진행, 아니면 중단 후 메세지 출력
  // inputAge가 nil이 아니면 진행, nil이면 중단 후 메세지 출력
  assert(inputAge != nil, "inputAge = nil")
  
  // 다중 조건인 경우 소괄호로 묶어서 작성
  assert((inputAge! > 0) && (inputAge! <= 100), "나이가 0세 이하 혹은 100세 초과입니다.")
  print("입력한 나이는 \(inputAge!)세 입니다.")
}

ageCheckWithAssert(inputAge: 50)

// inputAge -1 입력 시 func 내부에서 print까지 못 가기도 하지만, 거기서 스크립트가 종료되기 때문에 아래 함수인 inputAge : nil도 실행하지 않음
ageCheckWithAssert(inputAge: -1) // Assertion failed: 나이가 0세 이하 혹은 100세 초과입니다.
ageCheckWithAssert(inputAge: nil) // Assertion failed: inputAge = nil

// * assert(_:_:file:line:)와 같은 역할을 하지만 실제 배포 환경에서도 동작하는 precondition(_:_:file:line:) 함수도 있음
```

## guard(빠른 종료 - Early Exit)

- guard를 사용하여 잘못된 값의 전달 시, 특정 실행구문을 빠르게 종료
    - assert와 달리 해당 구문만 종료될 뿐, 스크립트 자체가 종료되지는 않음
- 디버깅 모드 뿐만 아니라 어떤 조건에서도 동작
- guard는 else가 반드시 있어야 하며, else 블럭 내부에는 특정 코드블럭을 종료하는 지시어(return, break 등)가 꼭 있어야 함
- 타입 캐스팅, 옵셔널과도 자주 사용됨
- 그 외에도 단순 조건 판단 후 빠르게 종료할 때도 용이

```swift
// guard
func ageCheckWithGuard(inputAge : Int?) {
  
  guard // 다중 조건 입력 시 &&가 아닌 ,로 구별
    let bindingAge = inputAge,
    // let 구문 다음에서 inputAge 대신에 이미 안전하게 추출이 완료된 bindingAge를 사용할 수 있음
    bindingAge <= 100,
    bindingAge > 0
  else {
    // K: guard문 밖에서도 bindingAge를 사용할 수 있는데, else 문에서는 사용이 불가함. 이유는 모르겠음
    if let age = inputAge { print("입력 오류, 입력한 나이는 \(age)")}
    else { print("입력 오류, 입력한 나이는 nil")}
    return
  }
  
  // if let 구문과 달리 추출된 옵셔널 값 bingingAge를 guard let 구문 밖에서도 활용 가능
  print("당신의 나이는 \(bindingAge)세 입니다.")
}

ageCheckWithGuard(inputAge: 50) // 당신의 나이는 50세 입니다.
ageCheckWithGuard(inputAge: 101) // 입력 오류, 입력한 나이는 101
ageCheckWithGuard(inputAge: nil) // 입력 오류, 입력한 나이는 nil

// while문 안에서도 사용 가능
var count = 1
while true {
  // guard 조건이 맞으면 else를 지나치고, 아니면 else문(break) 실행
  guard count < 3
  else { break }
  
  print(count)
  count += 1
} // 1 // 2

count = 1
// K : while문에 조건을 서술해도 같은 결과가 나오는데, while문에서의 guard의 차별점은 모르겠음
while count < 5 {
  if count >= 3 {break}
  print(count)
  count += 1
} // 1 // 2

// dictionary 타입은 key가 없을수도 있기 때문에 무조건 옵셔널 반환
func funcIntroduceDictionary(info: [String:Any]) {
  // 추출한 name이 nil이 아니고, String 타입도 맞으면 패스, 아니면 else 구문 작동
  guard let name = info["name"] as? String
  else {
    return print("이름이 잘못 입력되었습니다.")
  }
  guard let age = info["age"] as? Int, age > 0
  else {
    return print("나이가 잘못 입력되었습니다.")
  }
  
  print("\(name) : \(age)")
}

// age가 Int가 아니어서 실패
funcIntroduceDictionary(info: ["name":"Kaz","age":"10"]) // 나이가 잘못 입력되었습니다.
// name key를 찾을수가 없어서(nil이어서) 실패
funcIntroduceDictionary(info: ["age": 10]) // 이름이 잘못 입력되었습니다.

funcIntroduceDictionary(info: ["name":"Kaz","age":10]) // Kaz : 10
```

- if let 과 guard의 옵셔널 바인딩 비교

```swift
// if let / guard let 차이

var someOptionalInt : Int? = 1

if let a = someOptionalInt {
  print(a)
}
// if let 구문 밖에서는 옵셔널 바인딩된 a를 사용할 수 없음
// print(a) // error: cannot find 'a' in scope

// K : 예제에서는 else 문 안에서 return을 사용할 수 있는데, 이 버전에서는 func가 아닌 곳에서의 return은 무효하다고 나옴. 버전의 차이로 예상

guard let b: Int = someOptionalInt else {
  return
}

// guard 구문 이후에도 바인딩 된 b를 사용할 수 있음
print(b) // 1

```
